version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: mhed.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    set PATH=C:\Python37-x64;C:\Python37-x64\Scripts;%PATH%

    set CI_DIR=%APPVEYOR_BUILD_FOLDER%\src\bin\%CONFIGURATION%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    7z a -m0=LZMA2 -mx9 -t7z -x!*.ico packaging\results\snapshot_%CI_HASH%.7z %CI_DIR%\*

    "%ProgramFiles(x86)%\Inno Setup 6\ISCC.exe" packaging\inno\mhed.iss
artifacts:
- path: packaging\results\mhed_*.7z
  name: snapshot
- path: packaging\results\mhed_*.exe
  name: innosetup
