version: 0.8.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
build:
  project: mhed.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: 7z a mhed_%APPVEYOR_REPO_COMMIT:~0,7%.7z %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%
artifacts:
- path: mhed_*.7z
  name: snapshot
