version: 0.8.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
init:
- cmd: git config --global core.autocrlf true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  project: mhed.sln
  parallel: true
  verbosity: normal
after_build:
- cmd: >-
    set CI_DIR=%APPVEYOR_BUILD_FOLDER%\src\bin\%CONFIGURATION%

    set CI_HASH=%APPVEYOR_REPO_COMMIT:~0,7%

    7z a mhed_%CI_HASH%.7z %CI_DIR%\*

    "%ProgramFiles(x86)%\Inno Setup 5\ISCC.exe" %CI_DIR%\mhed.iss

    move "%CI_DIR%\Output\*.exe" .
artifacts:
- path: mhed_*.7z
  name: snapshot
- path: mhed_*.exe
  name: innosetup
