#
# SPDX-FileCopyrightText: 2011-2021 EasyCoding Team
#
# SPDX-License-Identifier: GPL-3.0-or-later
#

name: Windows CI

on:
  push:
    branches:
    - 'master'
    - 'dev'
  pull_request:
    branches:
    - 'master'
    - 'dev'

jobs:
  build:
    name: Build project using .NET Framework
    runs-on: windows-latest
    steps:
    - name: Fetching sources
      uses: actions/checkout@v2
    - name: Configuring MSBuild service
      uses: microsoft/setup-msbuild@v1.1
    - name: Restoring dependencies with NuGet
      run: |
        nuget restore mhed.sln
    - name: Building project with MSBuild
      run: |
        msbuild /p:Configuration=Release mhed.sln
